// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.1
// source: proto/elastic_service.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CitySearchNameResponse_ResponseCode int32

const (
	CitySearchNameResponse_SUCCESS_NAME        CitySearchNameResponse_ResponseCode = 0
	CitySearchNameResponse_FUZZY_NAME          CitySearchNameResponse_ResponseCode = 1
	CitySearchNameResponse_EMPTY_NAME          CitySearchNameResponse_ResponseCode = 2
	CitySearchNameResponse_INTERNAL_ERROR_NAME CitySearchNameResponse_ResponseCode = 3
)

// Enum value maps for CitySearchNameResponse_ResponseCode.
var (
	CitySearchNameResponse_ResponseCode_name = map[int32]string{
		0: "SUCCESS_NAME",
		1: "FUZZY_NAME",
		2: "EMPTY_NAME",
		3: "INTERNAL_ERROR_NAME",
	}
	CitySearchNameResponse_ResponseCode_value = map[string]int32{
		"SUCCESS_NAME":        0,
		"FUZZY_NAME":          1,
		"EMPTY_NAME":          2,
		"INTERNAL_ERROR_NAME": 3,
	}
)

func (x CitySearchNameResponse_ResponseCode) Enum() *CitySearchNameResponse_ResponseCode {
	p := new(CitySearchNameResponse_ResponseCode)
	*p = x
	return p
}

func (x CitySearchNameResponse_ResponseCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CitySearchNameResponse_ResponseCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_elastic_service_proto_enumTypes[0].Descriptor()
}

func (CitySearchNameResponse_ResponseCode) Type() protoreflect.EnumType {
	return &file_proto_elastic_service_proto_enumTypes[0]
}

func (x CitySearchNameResponse_ResponseCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CitySearchNameResponse_ResponseCode.Descriptor instead.
func (CitySearchNameResponse_ResponseCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_elastic_service_proto_rawDescGZIP(), []int{2, 0}
}

type CitySearchCoordsResponse_ResponseCode int32

const (
	CitySearchCoordsResponse_SUCCESS_COORDS        CitySearchCoordsResponse_ResponseCode = 0
	CitySearchCoordsResponse_EMPTY_COORDS          CitySearchCoordsResponse_ResponseCode = 1
	CitySearchCoordsResponse_INVALID_COORDS        CitySearchCoordsResponse_ResponseCode = 2
	CitySearchCoordsResponse_INTERNAL_ERROR_COORDS CitySearchCoordsResponse_ResponseCode = 3
)

// Enum value maps for CitySearchCoordsResponse_ResponseCode.
var (
	CitySearchCoordsResponse_ResponseCode_name = map[int32]string{
		0: "SUCCESS_COORDS",
		1: "EMPTY_COORDS",
		2: "INVALID_COORDS",
		3: "INTERNAL_ERROR_COORDS",
	}
	CitySearchCoordsResponse_ResponseCode_value = map[string]int32{
		"SUCCESS_COORDS":        0,
		"EMPTY_COORDS":          1,
		"INVALID_COORDS":        2,
		"INTERNAL_ERROR_COORDS": 3,
	}
)

func (x CitySearchCoordsResponse_ResponseCode) Enum() *CitySearchCoordsResponse_ResponseCode {
	p := new(CitySearchCoordsResponse_ResponseCode)
	*p = x
	return p
}

func (x CitySearchCoordsResponse_ResponseCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CitySearchCoordsResponse_ResponseCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_elastic_service_proto_enumTypes[1].Descriptor()
}

func (CitySearchCoordsResponse_ResponseCode) Type() protoreflect.EnumType {
	return &file_proto_elastic_service_proto_enumTypes[1]
}

func (x CitySearchCoordsResponse_ResponseCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CitySearchCoordsResponse_ResponseCode.Descriptor instead.
func (CitySearchCoordsResponse_ResponseCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_elastic_service_proto_rawDescGZIP(), []int{3, 0}
}

type Coords struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lat float32 `protobuf:"fixed32,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon float32 `protobuf:"fixed32,2,opt,name=lon,proto3" json:"lon,omitempty"`
}

func (x *Coords) Reset() {
	*x = Coords{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_elastic_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Coords) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coords) ProtoMessage() {}

func (x *Coords) ProtoReflect() protoreflect.Message {
	mi := &file_proto_elastic_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coords.ProtoReflect.Descriptor instead.
func (*Coords) Descriptor() ([]byte, []int) {
	return file_proto_elastic_service_proto_rawDescGZIP(), []int{0}
}

func (x *Coords) GetLat() float32 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Coords) GetLon() float32 {
	if x != nil {
		return x.Lon
	}
	return 0
}

type City struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Coords     *Coords `protobuf:"bytes,1,opt,name=coords,proto3" json:"coords,omitempty"`
	District   string  `protobuf:"bytes,2,opt,name=district,proto3" json:"district,omitempty"`
	Name       string  `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Population int32   `protobuf:"varint,4,opt,name=population,proto3" json:"population,omitempty"`
	Subject    string  `protobuf:"bytes,5,opt,name=subject,proto3" json:"subject,omitempty"`
}

func (x *City) Reset() {
	*x = City{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_elastic_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *City) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*City) ProtoMessage() {}

func (x *City) ProtoReflect() protoreflect.Message {
	mi := &file_proto_elastic_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use City.ProtoReflect.Descriptor instead.
func (*City) Descriptor() ([]byte, []int) {
	return file_proto_elastic_service_proto_rawDescGZIP(), []int{1}
}

func (x *City) GetCoords() *Coords {
	if x != nil {
		return x.Coords
	}
	return nil
}

func (x *City) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *City) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *City) GetPopulation() int32 {
	if x != nil {
		return x.Population
	}
	return 0
}

func (x *City) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

type CitySearchNameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    CitySearchNameResponse_ResponseCode `protobuf:"varint,1,opt,name=code,proto3,enum=api.CitySearchNameResponse_ResponseCode" json:"code,omitempty"`
	Options []*City                             `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty"`
}

func (x *CitySearchNameResponse) Reset() {
	*x = CitySearchNameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_elastic_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CitySearchNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CitySearchNameResponse) ProtoMessage() {}

func (x *CitySearchNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_elastic_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CitySearchNameResponse.ProtoReflect.Descriptor instead.
func (*CitySearchNameResponse) Descriptor() ([]byte, []int) {
	return file_proto_elastic_service_proto_rawDescGZIP(), []int{2}
}

func (x *CitySearchNameResponse) GetCode() CitySearchNameResponse_ResponseCode {
	if x != nil {
		return x.Code
	}
	return CitySearchNameResponse_SUCCESS_NAME
}

func (x *CitySearchNameResponse) GetOptions() []*City {
	if x != nil {
		return x.Options
	}
	return nil
}

type CitySearchCoordsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    CitySearchCoordsResponse_ResponseCode `protobuf:"varint,1,opt,name=code,proto3,enum=api.CitySearchCoordsResponse_ResponseCode" json:"code,omitempty"`
	Options []*City                               `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty"`
}

func (x *CitySearchCoordsResponse) Reset() {
	*x = CitySearchCoordsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_elastic_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CitySearchCoordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CitySearchCoordsResponse) ProtoMessage() {}

func (x *CitySearchCoordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_elastic_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CitySearchCoordsResponse.ProtoReflect.Descriptor instead.
func (*CitySearchCoordsResponse) Descriptor() ([]byte, []int) {
	return file_proto_elastic_service_proto_rawDescGZIP(), []int{3}
}

func (x *CitySearchCoordsResponse) GetCode() CitySearchCoordsResponse_ResponseCode {
	if x != nil {
		return x.Code
	}
	return CitySearchCoordsResponse_SUCCESS_COORDS
}

func (x *CitySearchCoordsResponse) GetOptions() []*City {
	if x != nil {
		return x.Options
	}
	return nil
}

type CityNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CityNameRequest) Reset() {
	*x = CityNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_elastic_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CityNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CityNameRequest) ProtoMessage() {}

func (x *CityNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_elastic_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CityNameRequest.ProtoReflect.Descriptor instead.
func (*CityNameRequest) Descriptor() ([]byte, []int) {
	return file_proto_elastic_service_proto_rawDescGZIP(), []int{4}
}

func (x *CityNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CoordsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lat    float32 `protobuf:"fixed32,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon    float32 `protobuf:"fixed32,2,opt,name=lon,proto3" json:"lon,omitempty"`
	Radius *string `protobuf:"bytes,3,opt,name=radius,proto3,oneof" json:"radius,omitempty"`
}

func (x *CoordsRequest) Reset() {
	*x = CoordsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_elastic_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CoordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordsRequest) ProtoMessage() {}

func (x *CoordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_elastic_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordsRequest.ProtoReflect.Descriptor instead.
func (*CoordsRequest) Descriptor() ([]byte, []int) {
	return file_proto_elastic_service_proto_rawDescGZIP(), []int{5}
}

func (x *CoordsRequest) GetLat() float32 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *CoordsRequest) GetLon() float32 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *CoordsRequest) GetRadius() string {
	if x != nil && x.Radius != nil {
		return *x.Radius
	}
	return ""
}

var File_proto_elastic_service_proto protoreflect.FileDescriptor

var file_proto_elastic_service_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x6c, 0x61, 0x73, 0x74, 0x69, 0x63, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61,
	0x70, 0x69, 0x22, 0x2c, 0x0a, 0x06, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x10, 0x0a, 0x03,
	0x6c, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6c, 0x61, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x6c, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6c, 0x6f, 0x6e,
	0x22, 0x95, 0x01, 0x0a, 0x04, 0x43, 0x69, 0x74, 0x79, 0x12, 0x23, 0x0a, 0x06, 0x63, 0x6f, 0x6f,
	0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x43, 0x6f, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x06, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x1a,
	0x0a, 0x08, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e,
	0x0a, 0x0a, 0x70, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x70, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x22, 0xd6, 0x01, 0x0a, 0x16, 0x43, 0x69, 0x74,
	0x79, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x28, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x23, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x09, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x52, 0x07, 0x6f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x59, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53,
	0x53, 0x5f, 0x4e, 0x41, 0x4d, 0x45, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x46, 0x55, 0x5a, 0x5a,
	0x59, 0x5f, 0x4e, 0x41, 0x4d, 0x45, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x45, 0x4d, 0x50, 0x54,
	0x59, 0x5f, 0x4e, 0x41, 0x4d, 0x45, 0x10, 0x02, 0x12, 0x17, 0x0a, 0x13, 0x49, 0x4e, 0x54, 0x45,
	0x52, 0x4e, 0x41, 0x4c, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x4e, 0x41, 0x4d, 0x45, 0x10,
	0x03, 0x22, 0xe4, 0x01, 0x0a, 0x18, 0x43, 0x69, 0x74, 0x79, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x43, 0x6f, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2a, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x43, 0x6f, 0x6f,
	0x72, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x23,
	0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x09, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x22, 0x63, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x5f, 0x43,
	0x4f, 0x4f, 0x52, 0x44, 0x53, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x45, 0x4d, 0x50, 0x54, 0x59,
	0x5f, 0x43, 0x4f, 0x4f, 0x52, 0x44, 0x53, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x49, 0x4e, 0x56,
	0x41, 0x4c, 0x49, 0x44, 0x5f, 0x43, 0x4f, 0x4f, 0x52, 0x44, 0x53, 0x10, 0x02, 0x12, 0x19, 0x0a,
	0x15, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x4e, 0x41, 0x4c, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f,
	0x43, 0x4f, 0x4f, 0x52, 0x44, 0x53, 0x10, 0x03, 0x22, 0x25, 0x0a, 0x0f, 0x43, 0x69, 0x74, 0x79,
	0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x5b, 0x0a, 0x0d, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x6c, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6c,
	0x61, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x03, 0x6c, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x06, 0x72, 0x61, 0x64, 0x69, 0x75, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x72, 0x61, 0x64, 0x69, 0x75, 0x73, 0x88, 0x01,
	0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x72, 0x61, 0x64, 0x69, 0x75, 0x73, 0x32, 0x94, 0x01, 0x0a,
	0x0a, 0x43, 0x69, 0x74, 0x79, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x41, 0x0a, 0x0c, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43,
	0x0a, 0x0e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x42, 0x79, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x73,
	0x12, 0x12, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_elastic_service_proto_rawDescOnce sync.Once
	file_proto_elastic_service_proto_rawDescData = file_proto_elastic_service_proto_rawDesc
)

func file_proto_elastic_service_proto_rawDescGZIP() []byte {
	file_proto_elastic_service_proto_rawDescOnce.Do(func() {
		file_proto_elastic_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_elastic_service_proto_rawDescData)
	})
	return file_proto_elastic_service_proto_rawDescData
}

var file_proto_elastic_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_elastic_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_elastic_service_proto_goTypes = []interface{}{
	(CitySearchNameResponse_ResponseCode)(0),   // 0: api.CitySearchNameResponse.ResponseCode
	(CitySearchCoordsResponse_ResponseCode)(0), // 1: api.CitySearchCoordsResponse.ResponseCode
	(*Coords)(nil),                   // 2: api.Coords
	(*City)(nil),                     // 3: api.City
	(*CitySearchNameResponse)(nil),   // 4: api.CitySearchNameResponse
	(*CitySearchCoordsResponse)(nil), // 5: api.CitySearchCoordsResponse
	(*CityNameRequest)(nil),          // 6: api.CityNameRequest
	(*CoordsRequest)(nil),            // 7: api.CoordsRequest
}
var file_proto_elastic_service_proto_depIdxs = []int32{
	2, // 0: api.City.coords:type_name -> api.Coords
	0, // 1: api.CitySearchNameResponse.code:type_name -> api.CitySearchNameResponse.ResponseCode
	3, // 2: api.CitySearchNameResponse.options:type_name -> api.City
	1, // 3: api.CitySearchCoordsResponse.code:type_name -> api.CitySearchCoordsResponse.ResponseCode
	3, // 4: api.CitySearchCoordsResponse.options:type_name -> api.City
	6, // 5: api.CitySearch.SearchByName:input_type -> api.CityNameRequest
	7, // 6: api.CitySearch.SearchByCoords:input_type -> api.CoordsRequest
	4, // 7: api.CitySearch.SearchByName:output_type -> api.CitySearchNameResponse
	5, // 8: api.CitySearch.SearchByCoords:output_type -> api.CitySearchCoordsResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_elastic_service_proto_init() }
func file_proto_elastic_service_proto_init() {
	if File_proto_elastic_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_elastic_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Coords); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_elastic_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*City); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_elastic_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CitySearchNameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_elastic_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CitySearchCoordsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_elastic_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CityNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_elastic_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CoordsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_elastic_service_proto_msgTypes[5].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_elastic_service_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_elastic_service_proto_goTypes,
		DependencyIndexes: file_proto_elastic_service_proto_depIdxs,
		EnumInfos:         file_proto_elastic_service_proto_enumTypes,
		MessageInfos:      file_proto_elastic_service_proto_msgTypes,
	}.Build()
	File_proto_elastic_service_proto = out.File
	file_proto_elastic_service_proto_rawDesc = nil
	file_proto_elastic_service_proto_goTypes = nil
	file_proto_elastic_service_proto_depIdxs = nil
}
