name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          debug: true
          script: |
            whoami
            cd ~/Elastic-Service
            git reset --hard
            git pull origin main
            cat << EOF > .env
            ELASTIC_USER=${{ secrets.ELASTIC_USER }}
            ELASTIC_PASSWORD=${{ secrets.ELASTIC_PASSWORD }}
            PORT=${{ secrets.ELASTIC_SERVICE_PORT }}
            ELASTIC_DISTANCE=${{ secrets.ELASTIC_DISTANCE }}
            ELASTICSEARCH_ADDRESS=${{ secrets.ELASTICSEARCH_ADDRESS }}
            EOF
            docker compose -f deploy.yml up --build -d --force-recreate